//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorBike
    {
        public int MotorId { get; set; }
        public string ModeofUse { get; set; }
        public int MotorReg { get; set; }
        public int MotorValue { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
